name: hetimascript
version: 0.0.1
description: A starting point for Dart libraries or applications.
dependencies:
  hetimacore:
    path: /Users/kiyohiro/dart/git/dart_hetimacore
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
